// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
)

const (
	// CheckConclusionFailed is a CheckConclusion of type failed.
	CheckConclusionFailed CheckConclusion = "failed"
	// CheckConclusionSucceeded is a CheckConclusion of type succeeded.
	CheckConclusionSucceeded CheckConclusion = "succeeded"
)

// String implements the Stringer interface.
func (x CheckConclusion) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x CheckConclusion) IsValid() bool {
	_, err := ParseCheckConclusion(string(x))
	return err == nil
}

var _CheckConclusionValue = map[string]CheckConclusion{
	"failed":    CheckConclusionFailed,
	"succeeded": CheckConclusionSucceeded,
}

// ParseCheckConclusion attempts to convert a string to a CheckConclusion.
func ParseCheckConclusion(name string) (CheckConclusion, error) {
	if x, ok := _CheckConclusionValue[name]; ok {
		return x, nil
	}
	return CheckConclusion(""), fmt.Errorf("%s is not a valid CheckConclusion", name)
}

const (
	// CheckStatusInProgress is a CheckStatus of type in_progress.
	CheckStatusInProgress CheckStatus = "in_progress"
	// CheckStatusCompleted is a CheckStatus of type completed.
	CheckStatusCompleted CheckStatus = "completed"
)

// String implements the Stringer interface.
func (x CheckStatus) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x CheckStatus) IsValid() bool {
	_, err := ParseCheckStatus(string(x))
	return err == nil
}

var _CheckStatusValue = map[string]CheckStatus{
	"in_progress": CheckStatusInProgress,
	"completed":   CheckStatusCompleted,
}

// ParseCheckStatus attempts to convert a string to a CheckStatus.
func ParseCheckStatus(name string) (CheckStatus, error) {
	if x, ok := _CheckStatusValue[name]; ok {
		return x, nil
	}
	return CheckStatus(""), fmt.Errorf("%s is not a valid CheckStatus", name)
}

const (
	// CheckSummaryStatusPending is a CheckSummaryStatus of type pending.
	CheckSummaryStatusPending CheckSummaryStatus = "pending"
	// CheckSummaryStatusPassed is a CheckSummaryStatus of type passed.
	CheckSummaryStatusPassed CheckSummaryStatus = "passed"
	// CheckSummaryStatusFailed is a CheckSummaryStatus of type failed.
	CheckSummaryStatusFailed CheckSummaryStatus = "failed"
)

// String implements the Stringer interface.
func (x CheckSummaryStatus) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x CheckSummaryStatus) IsValid() bool {
	_, err := ParseCheckSummaryStatus(string(x))
	return err == nil
}

var _CheckSummaryStatusValue = map[string]CheckSummaryStatus{
	"pending": CheckSummaryStatusPending,
	"passed":  CheckSummaryStatusPassed,
	"failed":  CheckSummaryStatusFailed,
}

// ParseCheckSummaryStatus attempts to convert a string to a CheckSummaryStatus.
func ParseCheckSummaryStatus(name string) (CheckSummaryStatus, error) {
	if x, ok := _CheckSummaryStatusValue[name]; ok {
		return x, nil
	}
	return CheckSummaryStatus(""), fmt.Errorf("%s is not a valid CheckSummaryStatus", name)
}
